#!/bin/bash

set -e

: "${PRIMARY_DOMAIN:?Need to set PRIMARY_DOMAIN}"
: "${WWW_DOMAIN:?Need to set WWW_DOMAIN}"
: "${SUBDOMAINS:?Need to set SUBDOMAINS}"
: "${SSL_EMAIL:?Need to set SSL_EMAIL}"

ENVIRONMENT="$1"
if [ -z "$ENVIRONMENT" ]; then
  echo "Usage: $0 [dev|production]"
  exit 1
fi

DOCKER_COMPOSE_FILE="docker-compose.yml"
NGINX_AVAILABLE_DIR=/etc/nginx/sites-available
NGINX_ENABLED_DIR=/etc/nginx/sites-enabled
NGINX_CONFIG_FILE=$NGINX_AVAILABLE_DIR/gyld

sudo mkdir -p "$NGINX_AVAILABLE_DIR" "$NGINX_ENABLED_DIR"

if ! command -v nginx >/dev/null 2>&1; then
  echo "NGINX is not installed. Please install it first."
  exit 1
fi

if ! command -v yq >/dev/null 2>&1; then
  echo "yq command not found. Please install it: sudo apt install yq"
  exit 1
fi

function get_host_port_from_compose() {
  local subdomainService="$1"
  local dcFile="$2"
  local hostPort=$(yq e ".services.$subdomainService.ports[0]" "$dcFile" | cut -d':' -f1)
  if [[ "$hostPort" == "null" || -z "$hostPort" ]]; then
    echo ""
  else
    echo "$hostPort"
  fi
}

MAIN_HTTP_BLOCK="server {
    listen 80;
    server_name $PRIMARY_DOMAIN $WWW_DOMAIN;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }
}"

MAIN_HTTPS_BLOCK=""
if [ "$ENVIRONMENT" = "production" ]; then
  MAIN_HTTPS_BLOCK="server {
      listen 443 ssl;
      server_name $PRIMARY_DOMAIN $WWW_DOMAIN;

      ssl_certificate /etc/letsencrypt/live/$PRIMARY_DOMAIN/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/$PRIMARY_DOMAIN/privkey.pem;

      location / {
          proxy_pass http://127.0.0.1:8080;
          proxy_set_header Host \$host;
          proxy_set_header X-Real-IP \$remote_addr;
          proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
      }
  }"
fi

SUBDOMAIN_CONFIG=""
IFS=' ' read -ra SUBDOMAIN_ARRAY <<< "$SUBDOMAINS"

for FULL_SUBDOMAIN in "${SUBDOMAIN_ARRAY[@]}"; do
  SUBDOMAIN_SERVICE_NAME=$(echo "$FULL_SUBDOMAIN" | cut -d '.' -f 1)
  HOST_PORT=$(get_host_port_from_compose "$SUBDOMAIN_SERVICE_NAME" "$DOCKER_COMPOSE_FILE")

  if [[ -z "$HOST_PORT" ]]; then
    echo "Warning: No port mapping found for '$SUBDOMAIN_SERVICE_NAME'. Skipping."
    continue
  fi

  SUBDOMAIN_HTTP_BLOCK="server {
      listen 80;
      server_name $FULL_SUBDOMAIN;

      location / {
          proxy_pass http://127.0.0.1:${HOST_PORT};
          proxy_set_header Host \$host;
          proxy_set_header X-Real-IP \$remote_addr;
          proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
      }
  }"

  SUBDOMAIN_HTTPS_BLOCK=""
  if [ "$ENVIRONMENT" = "production" ]; then
  SUBDOMAIN_HTTPS_BLOCK="server {
      listen 443 ssl;
      server_name $FULL_SUBDOMAIN;

      ssl_certificate /etc/letsencrypt/live/$PRIMARY_DOMAIN/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/$PRIMARY_DOMAIN/privkey.pem;

      location / {
          proxy_pass http://127.0.0.1:${HOST_PORT};
          proxy_set_header Host \$host;
          proxy_set_header X-Real-IP \$remote_addr;
          proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
      }
  }"
  fi

  SUBDOMAIN_CONFIG="$SUBDOMAIN_CONFIG
$SUBDOMAIN_HTTP_BLOCK
$SUBDOMAIN_HTTPS_BLOCK
"
done

sudo bash -c "cat > $NGINX_CONFIG_FILE" <<EOF
# Generated by deploy_nginx_config.sh for $ENVIRONMENT
$MAIN_HTTP_BLOCK
$MAIN_HTTPS_BLOCK
$SUBDOMAIN_CONFIG
EOF

sudo ln -sf "$NGINX_CONFIG_FILE" "$NGINX_ENABLED_DIR/gyld"
sudo nginx -t && sudo systemctl reload nginx

echo "NGINX configuration applied successfully for environment=$ENVIRONMENT."
