services:
  www:
    container_name: mws_www
    build:
      context: .
      dockerfile: docker/mws/Dockerfile
      args:
        - DOTENV_PRIVATE_KEY=$DOTENV_PRIVATE_KEY
        - DOTENV_PRIVATE_KEY_PRODUCTION=$DOTENV_PRIVATE_KEY_PRODUCTION
    working_dir: "/app/TiddlyWiki5"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - WIKI_FOLDER=www
    volumes:
      - ./wikis/www:/app/TiddlyWiki5/editions/www:rw
      - ./.env:/app/TiddlyWiki5/.env:ro
    ports:
      - "8080:8080"
    networks:
      - mws_net
  sdm:
    container_name: mws_sdm
    build:
      context: .
      dockerfile: docker/mws/Dockerfile
      args:
        - DOTENV_PRIVATE_KEY=$DOTENV_PRIVATE_KEY
        - DOTENV_PRIVATE_KEY_PRODUCTION=$DOTENV_PRIVATE_KEY_PRODUCTION
    working_dir: "/app/TiddlyWiki5"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - WIKI_FOLDER=sdm
    volumes:
      - ./wikis/sdm:/app/TiddlyWiki5/editions/sdm:rw
      - ./.env:/app/TiddlyWiki5/.env:ro
    ports:
      - "8081:8080"
    networks:
      - mws_net
  silat:
    container_name: mws_silat
    build:
      context: .
      dockerfile: docker/mws/Dockerfile
      args:
        - DOTENV_PRIVATE_KEY=$DOTENV_PRIVATE_KEY
        - DOTENV_PRIVATE_KEY_PRODUCTION=$DOTENV_PRIVATE_KEY_PRODUCTION
    working_dir: "/app/TiddlyWiki5"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - WIKI_FOLDER=silat
    volumes:
      - ./wikis/silat:/app/TiddlyWiki5/editions/silat:rw
      - ./.env:/app/TiddlyWiki5/.env:ro
    ports:
      - "8082:8080"
    networks:
      - mws_net
networks:
  mws_net:
    driver: bridge
